---
build_from:
  aarch64: ghcr.io/shaderhoth/python-matter-server:latest
  amd64: ghcr.io/shaderhoth/python-matter-server:latest
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.5.0
